import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  Map, Gauge, Code2, BookOpen, Sparkles, ArrowRight, CheckCircle2,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'

const features = [
  { icon: Map, title: 'AI Roadmaps', desc: 'Personalized week-by-week learning plans generated by Gemini, tuned to your degree, skills, and target career.' },
  { icon: Gauge, title: 'Skill Gap Analysis', desc: 'A readiness score plus the exact skills you are missing for your target role, ranked by learning order.' },
  { icon: Code2, title: 'Projects & Certifications', desc: 'Portfolio-worthy project ideas with tech stacks, and certifications that actually matter for freshers.' },
  { icon: BookOpen, title: 'Curated Free Resources', desc: 'Documentation, courses, and practice links matched to every week of your plan — free options first.' },
]

const steps = [
  { title: 'Tell us about you', desc: 'Share your degree, skills, and dream career in a 2-minute assessment.' },
  { title: 'Get your roadmap', desc: 'Gemini builds a week-by-week plan with projects, certs, and free resources.' },
  { title: 'Follow the plan', desc: 'Work through focused weekly sprints with projects and curated resources.' },
  { title: 'Land the offer', desc: 'Walk in ready — with real projects shipped and a clear story to tell.' },
]

const faqs = [
  { q: 'Is this free to use?', a: 'The core roadmap generator is free to start. Some advanced features may require a paid plan as you scale usage.' },
  { q: 'How is my roadmap personalized?', a: 'We combine your assessment answers with live industry data and feed it to Gemini with a structured prompt, so every plan is specific to your starting point and goal.' },
  { q: 'Can I change my target career later?', a: 'Yes — generate as many roadmaps as you want; each is cached so re-running the same inputs is instant.' },
  { q: 'Is my data private?', a: 'Your profile and roadmaps are stored securely with row-level security, so only you can access your own data.' },
]

export function LandingPage() {
  return (
    <div>
      {/* Hero */}
      <section className="mx-auto max-w-7xl px-6 pt-24 pb-20 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <span className="inline-flex items-center gap-2 rounded-full border border-[hsl(var(--border))] px-4 py-1.5 text-sm text-[hsl(var(--muted-foreground))] mb-6">
            <Sparkles className="h-3.5 w-3.5 text-[hsl(var(--primary))]" />
            AI-powered career intelligence for freshers
          </span>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight max-w-4xl mx-auto leading-tight">
            Your dream career, <span className="gradient-text">mapped week by week</span>
          </h1>
          <p className="mt-6 text-lg text-[hsl(var(--muted-foreground))] max-w-2xl mx-auto">
            Mentor Roadmap Pro turns your skills and goals into a personalized learning plan — weekly
            sprints, portfolio projects, certifications, and free resources included.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <Link to="/sign-up">
              <Button size="lg">
                Build my roadmap <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link to="/sign-in">
              <Button size="lg" variant="outline">I already have an account</Button>
            </Link>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <h2 className="text-3xl font-bold text-center mb-3">Everything you need to get hired</h2>
        <p className="text-center text-[hsl(var(--muted-foreground))] mb-12">One platform, from skill gap to offer letter.</p>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">
          {features.map((f) => (
            <Card key={f.title} className="hover:shadow-md transition-shadow">
              <CardHeader>
                <f.icon className="h-8 w-8 text-[hsl(var(--primary))] mb-2" />
                <CardTitle>{f.title}</CardTitle>
                <CardDescription>{f.desc}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </section>

      {/* Workflow */}
      <section className="mx-auto max-w-7xl px-6 py-20 bg-[hsl(var(--muted))]/40 rounded-3xl">
        <h2 className="text-3xl font-bold text-center mb-12">How it works</h2>
        <div className="grid md:grid-cols-4 gap-6">
          {steps.map((s, i) => (
            <div key={s.title} className="relative">
              <div className="text-4xl font-bold text-[hsl(var(--primary))]/30 mb-2">{String(i + 1).padStart(2, '0')}</div>
              <h3 className="font-semibold mb-1">{s.title}</h3>
              <p className="text-sm text-[hsl(var(--muted-foreground))]">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Testimonials */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <h2 className="text-3xl font-bold text-center mb-12">Freshers who found their path</h2>
        <div className="grid md:grid-cols-3 gap-5">
          {[
            { name: 'Priya S.', role: 'SDE-1, Bengaluru', quote: 'The weekly plan kept me from getting lost in a sea of tutorials.' },
            { name: 'Arjun M.', role: 'Data Analyst, Chennai', quote: 'The skill-gap analysis told me exactly what to learn first. No more guesswork.' },
            { name: 'Fatima K.', role: 'Frontend Dev, Hyderabad', quote: 'Four weeks in, I had shipped two portfolio projects straight off my roadmap.' },
          ].map((t) => (
            <Card key={t.name}>
              <CardContent className="pt-6">
                <p className="text-sm italic mb-4">&ldquo;{t.quote}&rdquo;</p>
                <p className="text-sm font-semibold">{t.name}</p>
                <p className="text-xs text-[hsl(var(--muted-foreground))]">{t.role}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-3xl px-6 py-20">
        <h2 className="text-3xl font-bold text-center mb-12">Frequently asked questions</h2>
        <div className="space-y-4">
          {faqs.map((f) => (
            <Card key={f.q}>
              <CardHeader>
                <CardTitle className="text-base flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 mt-1 text-[hsl(var(--primary))] shrink-0" />
                  {f.q}
                </CardTitle>
                <CardDescription className="pl-6">{f.a}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-4xl px-6 py-24 text-center">
        <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to build your roadmap?</h2>
        <p className="text-[hsl(var(--muted-foreground))] mb-8">It takes two minutes to get your first AI-generated plan.</p>
        <Link to="/sign-up">
          <Button size="lg">Get started free <ArrowRight className="h-4 w-4" /></Button>
        </Link>
      </section>
    </div>
  )
}
